[package]
authors = ["Zondax AG <info@zondax.ch>"]
name = "rslib"
version = "0.0.1"
edition = "2018"
readme = "README.md"

[lib]
name = "rslib"
crate-type = ["staticlib"]

[dependencies]
jubjub = { version = "0.10.0", default-features = false }

[target.thumbv6m-none-eabi.dev-dependencies]
panic-halt = "0.2.0"

[profile.release]
lto = "fat"
codegen-units = 1
debug=true
opt-level = "s"
panic = "abort"

[profile.dev]
panic = "abort"
debug=true

