[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
   "--emit", "asm",
   "-C", "relocation-model=ropi",
   "-C", "link-arg=-nostartfiles",
   "-C", "link-arg=-Tlink.ld",
   "-C", "inline-threshold=0"
]

# rustflags required in order to bolos-sys won't compile. Required in this project to use lazy_static
# - rustflags = ["-Ctarget-feature=-crt-static"]
# Reference: https://github.com/rust-lang/rust-bindgen/issues/2360#issuecomment-1595909134
[host]
rustflags = ["-Ctarget-feature=-crt-static", "-Cdebuginfo=2"]

# Needed for the embedded alloc feature, which enables the global alloc using the stack memory
# Come from this example to use ironfish-frost on ledger devices
# - build-std=["alloc"]
# - build-std-features=["compiler-builtins-mem"]
# Reference: https://github.com/iron-fish/ironfish-frost-ledger/tree/ad03ed83b5f2ebf4f494ae260fa1cf81c4599d58
# -----
# These two flags need to be true, otherwise bolos-sys crate won't compile. Required in this project to use lazy_static
# - target-applies-to-host = true
# - host-config = true
# Reference: https://github.com/rust-lang/rust-bindgen/issues/2360#issuecomment-1595909134
[unstable]
build-std=["core", "alloc"]
build-std-features=["panic_immediate_abort", "compiler-builtins-mem"]
target-applies-to-host = true
host-config = true

